extends Node3D
# Generated by build_godot_project.py
# Procedurally builds a 12x12 voxel world using BoxMesh + MeshInstance3D.
# Seeded for reproducibility so AI dataset captures are bitwise-identical.

const GRID: int = 12
const VOXEL_SIZE: float = 1.0
const SEED: int = 7

func _ready() -> void:
    seed(SEED)
    var palette := [
        Color(0.182, 0.482, 0.484),  # teal
        Color(0.851, 0.643, 0.255),  # amber
        Color(0.337, 0.549, 0.337),  # green
        Color(0.392, 0.322, 0.541),  # violet
    ]
    for i in range(GRID):
        for j in range(GRID):
            var h := 1 + (hash(Vector2i(i, j)) % 3)
            if i % 5 == 0 and j % 5 == 0:
                h += 2
            for z in range(h):
                _add_voxel(i, z, j, palette[(i + j + z) % palette.size()])

    # Ready signal for headless captures
    if Engine.has_singleton("AssetExporter"):
        var exporter = Engine.get_singleton("AssetExporter")
        exporter.call("export_gltf", self, "res://build/world.gltf")

func _add_voxel(x: int, y: int, z: int, color: Color) -> void:
    var mi := MeshInstance3D.new()
    var box := BoxMesh.new()
    box.size = Vector3(VOXEL_SIZE, VOXEL_SIZE, VOXEL_SIZE)
    mi.mesh = box

    var mat := StandardMaterial3D.new()
    mat.albedo_color = color
    mat.roughness = 0.85
    mi.material_override = mat

    mi.position = Vector3(x * VOXEL_SIZE, y * VOXEL_SIZE, z * VOXEL_SIZE)
    add_child(mi)
